#Gradle
org.gradle.jvmargs=-Xmx4G
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.daemon=true
org.gradle.parallel=true

#Kotlin
kotlin.daemon.jvmargs=-Xmx4G
kotlin.native.binary.gc=cms

#KotlinX
kotlinx.atomicfu.enableJvmIrTransformation=true

#Android
android.useAndroidX=true

# Application release configuration
application.version.name=1.0.0
application.version.code=1
application.android.compile_sdk=37
application.android.min_sdk=28
application.android.target_sdk=37

application.database.version=1
