import org.jetbrains.kotlin.gradle.plugin.mpp.KotlinNativeTarget

plugins {
    id("org.jetbrains.kotlin.multiplatform")
    id("org.jetbrains.kotlin.plugin.compose")
}

kotlin {
    iosArm64()
    iosSimulatorArm64()

    sourceSets {
        iosMain.dependencies {
            api(project(":sharedUI"))
            implementation(libs.ktor.client.darwin)
        }
    }

    targets
        .withType<KotlinNativeTarget>()
        .matching { it.konanTarget.family.isAppleFamily }
        .configureEach {
            binaries {
                framework {
                    baseName = "IosApp"
                    isStatic = true
                    export(project(":sharedUI"))
                }
            }
        }
}

val xcodeVersionConfig = layout.projectDirectory.file("XCodeProject/application-version.xcconfig")

val generateXcodeVersionConfig by tasks.registering {
    description = "generate xcode config file."
    inputs.property("application.version.name", application_version_name)
    inputs.property("application.version.code", application_version_code)
    outputs.file(xcodeVersionConfig)

    doLast {
        xcodeVersionConfig.asFile.writeText(
            """
            // Generated by :iosApp:generateXcodeVersionConfig. Do not edit manually.
            MARKETING_VERSION = $application_version_name
            CURRENT_PROJECT_VERSION = $application_version_code
            """.trimIndent() + "\n"
        )
    }
}

tasks.matching { it.name == "embedAndSignAppleFrameworkForXcode" }.configureEach {
    dependsOn(generateXcodeVersionConfig)
}
